### ISSUE TITLE
--expires options does not work.

### ISSUE THREAD

**Issue by VincentWo** [Askia/askia-slack-poll#3]
The `--expires` option does not work at the moment.
Steps to reproduce:
1. Type /askia "What ya wanna drink on Friday?" Wine Beer Water --expires "1d 2h"
2. Try to vote on any option.
3. You will get (even though 1d didn't pass):
> Poll error
> The ability to vote to this poll has expired

This should be fixed by changing Line 134 in vote.js. At the moment the test returns always true (because the second part of the comparison just calculates `poll.expires`, a positive value). The right test seems to be `date.getTime() < new Date.getTime()` because the poll is expired when the expiration date lies in the past.

**Comment by ysaskia** [comment]
Thank you. Will fix it soon, or if you want you can open a pull request and will merge it.

**Comment by VincentWo** [comment]
This is my first try at a pull request at github and I don't have anything to test the javascript code on my machine. 
I hope this helps anyway :)

**Comment by ysaskia** [comment]
And thank you for your help ;)
